default_stages: [commit]
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-added-large-files
            name: Check for large added files
          - id: end-of-file-fixer
            name: Ensure correct end of file

    - repo: local
      hooks:
          - id: prettier-format
            name: Prettier formatting
            language: system
            exclude_types:
                - python
                - image
                - shell
            entry: pnpm exec prettier --write

          - id: clang-format
            name: C++ Formatting
            language: system
            files: ^(esp|simulator)/.*\.(c|cpp|h|hpp)$
            entry: clang-format -i

          - id: frontend-eslint
            name: ESLint frontend
            language: system
            files: ^frontend/.*\.tsx?$
            entry: pnpm exec eslint --fix
