site_name: SunTransit
site_dir: docs_build
site_url: https://suntrans.it
repo_url: https://github.com/joined/suntransit
nav:
    - Home: index.md
    - Usage: usage.md
    - Development: development.md
theme:
    name: material
    palette:
        scheme: slate
        primary: yellow
        accent: deep orange
markdown_extensions:
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.superfences
plugins:
    - glightbox
hooks:
    - docs/hooks.py
