site_name: SunTransit
site_dir: docs_build
site_url: https://suntrans.it
repo_url: https://github.com/joined/suntransit
nav:
    - Home: index.md
    - Usage: usage.md
    - Development: development.md
theme:
    name: material
    logo: icon.svg
    favicon: favicon.png
    custom_dir: mkdocs_theme_overrides
    palette:
        scheme: slate
        primary: yellow
        accent: deep orange
    features:
        - navigation.instant
markdown_extensions:
    # Python Markdown
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - toc:
          permalink: true

    # Python Markdown Extensions
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
plugins:
    - glightbox
    - gen-files:
          scripts:
              - docs/gen_index.py
