site_name: SunTransit
site_dir: docs_build
site_url: https://suntrans.it
repo_url: https://github.com/joined/suntransit
nav:
    - Home: index.md
    - Usage: usage.md
    - Installer: installer.md
    - Development: development.md
    - Related projects: related.md
theme:
    name: material
    logo: icon.svg
    favicon: favicon.png
    custom_dir: mkdocs/theme_overrides
    palette:
        scheme: slate
        primary: yellow
        accent: deep orange
    features:
        - navigation.instant
extra_javascript:
    - path: https://unpkg.com/esp-web-tools@9/dist/web/install-button.js?module
      type: module
extra_css:
    - css/extra.css
watch:
    - mkdocs/
markdown_extensions:
    # Python Markdown
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - toc:
          permalink: true

    # Python Markdown Extensions
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
plugins:
    - search
    - glightbox
    - gen-files:
          scripts:
              - mkdocs/gen_index.py
hooks:
    - mkdocs/gen_manifest.py
