name: Build ESP binaries
description: Build ESP binaries

# TODO IDF version should be a parameter to this action

runs:
    using: 'composite'
    steps:
        - uses: pnpm/action-setup@v2
          with:
              version: latest

        - name: Install node
          uses: actions/setup-node@v4
          with:
              node-version: '20.10.0'
              cache: 'pnpm'

        - name: Install frontend dependencies and build frontend
          run: |
              pnpm i
              pnpm build
          shell: bash

        - name: Cache ccache
          uses: actions/cache@v4
          with:
              path: .ccache
              key: ccache-${{ runner.os }}-esp32-idf551-${{ hashFiles('**/CMakeLists.txt', 'sdkconfig.defaults', 'dependencies.lock') }}

        - name: Cache managed components
          uses: actions/cache@v4
          with:
              path: managed_components
              key: managed_components-${{ runner.os }}-${{ hashFiles('dependencies.lock') }}

        - name: Pull and cache Docker image
          shell: bash
          run: |
              IMAGE="espressif/idf:v5.5.1"
              docker pull "$IMAGE"

        - name: esp-idf build and merge firmware
          shell: bash
          run: |
              set -euo pipefail
              IMAGE="espressif/idf:v5.5.1"

              docker run --rm -t \
                -e IDF_TARGET="esp32" \
                -e IDF_CCACHE_ENABLE=1 \
                -e CCACHE_DIR="/app/${{ github.repository }}/.ccache" \
                -e GITHUB_ACTIONS=true \
                -v "${GITHUB_WORKSPACE}:/app/${{ github.repository }}" \
                -w "/app/${{ github.repository }}" \
                "$IMAGE" \
                bash -lc '
                  git config --global --add safe.directory "*"
                  echo "Using ccache dir: $CCACHE_DIR"
                  ccache -z || true
                  idf.py build
                  echo
                  ccache -s || true
                  cd scripts && ./merge_firmware.sh
                '
