name: CI

on: [push]

env:
  ESP_IDF_VERSION: v5.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'
        cache: 'yarn'
        cache-dependency-path: 'frontend/yarn.lock'
    - name: Install frontend dependencies and build frontend
      run: |
        cd frontend
        yarn install
        yarn build
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Generate server embeds
      run: python generate_server_embeds.py
    - name: Cache esp-idf build
      uses: actions/cache@v3
      with:
        path: "build"
        key: ${{ runner.os }}-build-v2
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ env.ESP_IDF_VERSION }}
        target: esp32
        path: '.'
