name: CI

on:
    - push
    - workflow_dispatch

permissions:
    contents: write

jobs:
    prettier:
        name: Prettier check
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - uses: pnpm/action-setup@v4
              with:
                  version: latest
            - name: Install node
              uses: actions/setup-node@v6
              with:
                  node-version: '20.10.0'
                  cache: 'pnpm'
            - name: Install frontend dependencies, check Prettier formatting
              run: |
                  pnpm i
                  pnpm lint:prettier

    cpp_format:
        name: C++ Formatting Check
        runs-on: ubuntu-latest
        strategy:
            matrix:
                path:
                    - 'esp'
                    - 'simulator'
        steps:
            - uses: actions/checkout@v5
            - name: Run clang-format style check for C/C++/Protobuf programs.
              uses: jidicula/clang-format-action@v4.15.0
              with:
                  clang-format-version: '17'
                  check-path: ${{ matrix.path }}

    frontend_eslint:
        name: ESLint Frontend
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - uses: pnpm/action-setup@v4
              with:
                  version: latest
            - name: Install node
              uses: actions/setup-node@v6
              with:
                  node-version: '20.10.0'
                  cache: 'pnpm'
            - name: Install frontend dependencies, run ESLint
              run: |
                  pnpm i
                  pnpm lint:frontend:eslint

    frontend_typescript:
        name: Typescript Frontend
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - uses: pnpm/action-setup@v4
              with:
                  version: latest
            - name: Install node
              uses: actions/setup-node@v6
              with:
                  node-version: '20.10.0'
                  cache: 'pnpm'
            - name: Install frontend dependencies, check typing
              run: |
                  pnpm i
                  pnpm lint:frontend:ts

    frontend_tests:
        name: Frontend Tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - uses: pnpm/action-setup@v4
              with:
                  version: latest
            - name: Install node
              uses: actions/setup-node@v6
              with:
                  node-version: '20.10.0'
                  cache: 'pnpm'
            - name: Install frontend dependencies, run tests
              run: |
                  pnpm i
                  pnpm test

    actionlint:
        name: Actionlint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - name: actionlint
              uses: raven-actions/actionlint@v2

    build_esp:
        name: Build and archive ESP firmware
        runs-on: ubuntu-latest
        strategy:
            matrix:
                idf_target: [esp32, esp32s3]

        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Build ESP binaries
              uses: ./.github/actions/build-esp
              with:
                  idf_target: ${{ matrix.idf_target }}
            - name: Archive build output artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: merged-firmware-${{ matrix.idf_target }}
                  path: build/merged-firmware.bin
                  compression-level: 0

    build_simulator:
        name: Build and archive simulator binaries
        timeout-minutes: 10
        runs-on: ubuntu-latest
        container: joined/sdl2:latest

        steps:
            - uses: actions/checkout@v5
            - uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/pip
                      ~/.platformio/.cache
                  key: pio-${{ runner.os }}-${{ hashFiles('platformio.ini') }}
            - uses: actions/setup-python@v6
              with:
                  python-version: '3.12'
            - name: Install PlatformIO Core
              run: pip3 install --upgrade platformio
            - name: Build PlatformIO Project
              run: |
                  pio run
            - name: Archive 480x320 simulator build
              uses: actions/upload-artifact@v4
              with:
                  name: simulator_480x320
                  path: .pio/build/3248s035c/program
                  compression-level: 0
            - name: Archive 800x480 simulator build
              uses: actions/upload-artifact@v4
              with:
                  name: simulator_800x480
                  path: .pio/build/8048s070c/program
                  compression-level: 0
