name: CI

on: [push]

env:
  ESP_IDF_VERSION: v5.1

jobs:
  build_esp:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '16.16.0'
        cache: 'yarn'
        cache-dependency-path: 'frontend/yarn.lock'
    - name: Install frontend dependencies and build frontend
      run: |
        cd frontend
        yarn install
        yarn build
    - name: Cache esp-idf build
      uses: actions/cache@v3
      with:
        path: "esp/build"
        key: ${{ runner.os }}-build-v2
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ env.ESP_IDF_VERSION }}
        target: esp32
        path: 'esp'

  build_simulator:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build PlatformIO Project
        run: |
          cd simulator
          pio run --verbose --environment emulator
